CURRENT_EXTRACTION_VERSION = "v1.12"

YOUTUBE_ARTIST_SEED = [
    # Rock / Alternative / Indie
    "The Beatles",
    "The Rolling Stones",
    "Led Zeppelin",
    "Pink Floyd",
    "David Bowie",
    "Bob Dylan",
    "The Beach Boys",
    "Neil Young",
    "The Velvet Underground",
    "Lou Reed",
    "Radiohead",
    "Talking Heads",
    "Joy Division",
    "New Order",
    "The Smiths",
    "Morrissey",
    "The Cure",
    "Sonic Youth",
    "Nirvana",
    "Kurt Cobain",
    "Pixies",
    "R.E.M.",
    "U2",
    "Arcade Fire",
    "My Bloody Valentine",
    "Cocteau Twins",
    "Slowdive",
    "Tame Impala",

    # Electronic / Experimental
    "Aphex Twin",
    "Brian Eno",
    "Kraftwerk",
    "Autechre",
    "Boards of Canada",
    "Burial",
    "Daft Punk",
    "Four Tet",
    "Flying Lotus",
    "Jon Hopkins",
    "Squarepusher",
    "Deadmau5",
    "The Chemical Brothers",
    "Underworld",
    "Portishead",
    "Massive Attack",

    # Hip-Hop / R&B
    "Kanye West",
    "Jay-Z",
    "Nas",
    "OutKast",
    "Andre 3000",
    "MF DOOM",
    "J Dilla",
    "Madlib",
    "Dr. Dre",
    "Kendrick Lamar",
    "A Tribe Called Quest",
    "Q-Tip",
    "The Notorious B.I.G.",
    "Tupac Shakur",
    "Lauryn Hill",
    "Missy Elliott",
    "Frank Ocean",
    "Tyler, The Creator",

    # Jazz / Soul / Funk
    "Miles Davis",
    "John Coltrane",
    "Alice Coltrane",
    "Herbie Hancock",
    "Charles Mingus",
    "Sun Ra",
    "Pharoah Sanders",
    "Ornette Coleman",
    "Nina Simone",
    "Aretha Franklin",
    "James Brown",
    "Stevie Wonder",
    "Marvin Gaye",
    "Prince",

    # Pop / Songwriting / Production Anchors
    "Michael Jackson",
    "Madonna",
    "Paul McCartney",
    "John Lennon",
    "George Harrison",
    "Elton John",
    "Kate Bush",
    "Phil Spector",
    "Max Martin",
    "Rick Rubin",
]

THE_STRIP_DENY = {
    "the who",
    "the cure",
    "the band",
}