CURRENT_EXTRACTION_VERSION = "v4.3"

YOUTUBE_ARTIST_SEED = [
    # Rock / Alternative / Indie
    "The Beatles",
    "The Rolling Stones",
    "Led Zeppelin",
    "Pink Floyd",
    "David Bowie",
    "Bob Dylan",
    "The Beach Boys",
    "Neil Young",
    "The Velvet Underground",
    "Lou Reed",
    "Radiohead",
    "Talking Heads",
    "Joy Division",
    "New Order",
    "The Smiths",
    "Morrissey",
    "The Cure",
    "Sonic Youth",
    "Nirvana",
    "Kurt Cobain",
    "Pixies",
    "R.E.M.",
    "U2",
    "Arcade Fire",
    "My Bloody Valentine",
    "Cocteau Twins",
    "Slowdive",
    "Tame Impala",

    # Electronic / Experimental
    "Aphex Twin",
    "Brian Eno",
    "Kraftwerk",
    "Autechre",
    "Boards of Canada",
    "Burial",
    "Daft Punk",
    "Four Tet",
    "Flying Lotus",
    "Jon Hopkins",
    "Squarepusher",
    "Deadmau5",
    "The Chemical Brothers",
    "Underworld",
    "Portishead",
    "Massive Attack",

    # Hip-Hop / R&B
    "Kanye West",
    "Jay-Z",
    "Nas",
    "OutKast",
    "Andre 3000",
    "MF DOOM",
    "J Dilla",
    "Madlib",
    "Dr. Dre",
    "Kendrick Lamar",
    "A Tribe Called Quest",
    "Q-Tip",
    "The Notorious B.I.G.",
    "Tupac Shakur",
    "Lauryn Hill",
    "Missy Elliott",
    "Frank Ocean",
    "Tyler, The Creator",

    # Jazz / Soul / Funk
    "Miles Davis",
    "John Coltrane",
    "Alice Coltrane",
    "Herbie Hancock",
    "Charles Mingus",
    "Sun Ra",
    "Pharoah Sanders",
    "Ornette Coleman",
    "Nina Simone",
    "Aretha Franklin",
    "James Brown",
    "Stevie Wonder",
    "Marvin Gaye",
    "Prince",

    # Pop / Songwriting / Production Anchors
    "Michael Jackson",
    "Madonna",
    "Paul McCartney",
    "John Lennon",
    "George Harrison",
    "Elton John",
    "Kate Bush",
    "Phil Spector",
    "Max Martin",
    "Rick Rubin",
]

THE_STRIP_DENY = {
    "the who",
    "the cure",
    "the band",
}

YOUTUBE_ARTIST_SEED_2 = [
    "Metallica",
    "Muse",
    "Queen",
    "Johann Sebastian Bach",
    "Iron Maiden",
    "Black Sabbath",
    "Depeche Mode",
    "Rush",
    "Eminem",
    "Linkin Park",
    "Rammstein",
    "Wolfgang Amadeus Mozart",
    "Deep Purple",
    "Coldplay",
    "AC/DC",
    "Pearl Jam",
    "Dream Theater",
    "The Doors",
    "Björk",
    "Nine Inch Nails",
    "The Prodigy",
    "Ludwig van Beethoven",
    "Nightwish",
    "Taylor Swift",
    "Bob Marley & The Wailers",
    "ABBA",
    "Guns N’ Roses",
    "2Pac",
    "Various Artists",
    "Genesis",
    "Red Hot Chili Peppers",
    "Lady Gaga",
    "Ye",
    "King Crimson",
    "Marilyn Manson",
    "Peter Gabriel",
    "Ramones",
    "Scorpions",
    "The Smashing Pumpkins",
    "Пётр Ильич Чайковский",
    "Mike Oldfield",
    "Pet Shop Boys",
    "Aerosmith",
    "The Who",
    "Megadeth",
    "Slayer",
    "Alanis Morissette",
    "Green Day",
    "Tom Waits",
    "Eric Clapton",
    "Armin van Buuren",
    "Rihanna",
    "Korn",
    "Beastie Boys",
    "Ennio Morricone",
    "Frank Zappa",
    "Mariah Carey",
    "Nick Cave & the Bad Seeds",
    "Buckethead",
    "Shakira",
    "Oasis",
    "Beyoncé",
    "Johnny Cash",
    "Jimi Hendrix",
    "Placebo",
    "Fleetwood Mac",
    "Bruce Springsteen",
    "Judas Priest",
    "Jethro Tull",
    "Ariana Grande",
    "Foo Fighters",
    "Antonio Vivaldi",
    "Mylène Farmer",
    "Yes",
    "Sting",
    "Beck",
    "Slipknot",
    "Ozzy Osbourne",
    "Def Leppard",
    "Tangerine Dream",
    "Grateful Dead",
    "Moby",
    "Hans Zimmer",
    "The Jimi Hendrix Experience",
    "DIR EN GREY",
    "The Killers",
    "Faith No More",
    "Lana Del Rey",
    "Tori Amos",
    "The Police",
    "Elliott Smith",
    "Johannes Brahms",
    "Alicia Keys",
    "Fryderyk Chopin",
    "Uriah Heep",
    "久石譲",
    "Сергей Васильевич Рахманинов",
    "Elvis Presley",
    "浜崎あゆみ",
    "Soundgarden",
    "Helloween",
    "King Gizzard & the Lizard Wizard",
    "Rage Against the Machine",
    "Blur",
    "Marillion",
    "Sepultura",
    "Motörhead",
    "Santana",
    "Electric Light Orchestra",
    "Vangelis",
    "植松伸夫",
    "John Williams",
    "Andrew Bird",
    "Franz Schubert",
    "Jean‐Michel Jarre",
    "Richard Wagner",
    "Bee Gees",
    "The Weeknd",
    "Gustav Mahler",
    "Simple Minds",
    "Whitesnake",
    "Дмитрий Дмитриевич Шостакович",
    "[unknown]",
    "They Might Be Giants",
    "Duran Duran",
    "Bon Jovi",
    "Roy Orbison",
    "Ween",
    "The Byrds",
    "Frank Sinatra",
    "Ed Sheeran",
    "Falco",
    "Kylie Minogue",
    "Kid Cudi",
    "BoA",
    "50 Cent",
    "Drake",
    "Cher",
    "Dave Matthews Band",
    "Eurythmics",
    "Giuseppe Verdi",
    "George Frideric Handel",
    "Lil Wayne",
    "Ella Fitzgerald",
    "Felix Mendelssohn",
    "坂本龍一",
    "Vader",
    "KISS",
    "Phish",
    "Wilco",
    "Cypress Hill",
    "Shania Twain",
    "twenty one pilots",
    "Chuck Berry",
    "川井憲次",
    "The Wedding Present",
    "Béla Bartók",
    "Joseph Haydn",
    "Anthrax",
    "Hawkwind",
    "Limp Bizkit",
    "Tina Turner",
    "鷺巣詩郎",
    "Above & Beyond",
    "Serge Gainsbourg",
    "Maurice Ravel",
    "Tom Petty and the Heartbreakers",
    "Nicki Minaj",
    "Van Morrison",
    "Toni Braxton",
    "Ministry",
    "Donna Summer",
    "Django Reinhardt",
    "Игорь Фёдорович Стравинский",
    "Claude Debussy",
    "Jerry Goldsmith",
    "TWICE",
    "Chicago",
    "Willie Nelson",
    "Olivia Newton‐John",
    "Toto",
    "Kool & the Gang",
    "Erasure",
    "Schiller",
    "Rage",
    "Antonín Dvořák",
    "Ricky Martin",
    "Joe Cocker",
    "Van Halen",
    "安室奈美恵",
    "Сергей Сергеевич Прокофьев",
    "Georg Philipp Telemann",
    "Bunbury",
    "Scooter",
    "The Monkees",
    "Jennifer Lopez",
    "Faithless",
    "Snoop Dogg",
    "Erik Satie",
    "Vicente Fernández",
]