1,[SUBJECT] Radiohead [CANDIDATE] John McGeoch [CONTEXT] Jonny Greenwood named the Magazine guitarist John McGeoch his biggest guitar influence.,1,positive
2,"[SUBJECT] Radiohead [CANDIDATE] DJ Shadow [CONTEXT] By the mid-1990s, Radiohead were adopting recording methods from hip-hop, inspired by the sampling work of DJ Shadow, and became interested in using computers to generate sounds.",1,positive
3,"[SUBJECT] Radiohead [CANDIDATE] Ennio Morricone [CONTEXT] Other influences include the soundtracks of Ennio Morricone, 1960s rock groups such as the Beatles and the Beach Boys, and Phil Spector's ""wall of sound"" production.",1,positive
4,"[SUBJECT] Radiohead [CANDIDATE] Beatles [CONTEXT] Other influences include the soundtracks of Ennio Morricone, 1960s rock groups such as the Beatles and the Beach Boys, and Phil Spector's ""wall of sound"" production.",1,positive
5,"[SUBJECT] Radiohead [CANDIDATE] Phil Spector [CONTEXT] Other influences include the soundtracks of Ennio Morricone, 1960s rock groups such as the Beatles and the Beach Boys, and Phil Spector's ""wall of sound"" production.",1,positive
6,"[SUBJECT] Radiohead [CANDIDATE] Aphex Twin [CONTEXT] The electronic music of Kid A was inspired by Yorke's admiration for artists signed to the record label Warp Records, such as Aphex Twin and Autechre.",1,positive
7,"[SUBJECT] Radiohead [CANDIDATE] Autechre [CONTEXT] The electronic music of Kid A was inspired by Yorke's admiration for artists signed to the record label Warp Records, such as Aphex Twin and Autechre.",1,positive
8,"[SUBJECT] Radiohead [CANDIDATE] Aphex Twin [CONTEXT] In 2013, Yorke named Aphex Twin as his biggest influence.",1,positive
9,[SUBJECT] Radiohead [CANDIDATE] Krzysztof Penderecki [CONTEXT] Jonny Greenwood cited the influence of the 20th-century classical composers Krzysztof Penderecki and Olivier Messiaen.,1,positive
10,[SUBJECT] Radiohead [CANDIDATE] Olivier Messiaen [CONTEXT] Jonny Greenwood cited the influence of the 20th-century classical composers Krzysztof Penderecki and Olivier Messiaen.,1,positive
11,"[SUBJECT] David Bowie [CANDIDATE] Little Richard [CONTEXT] His early compositions and performances were strongly influenced by rock and roll singers like Little Richard and Elvis Presley, and also the wider world of show business.",1,positive
12,"[SUBJECT] David Bowie [CANDIDATE] Elvis Presley [CONTEXT] His early compositions and performances were strongly influenced by rock and roll singers like Little Richard and Elvis Presley, and also the wider world of show business.",1,positive
13,"[SUBJECT] Bob Dylan [CANDIDATE] Jacques Levy [CONTEXT] Many of Desire's songs featuring a travelogue-like narrative style, influenced by Dylan's new collaborator, playwright Jacques Levy.",1,positive
14,"[SUBJECT] The Beatles [CANDIDATE] Yoko Ono [CONTEXT] Lennon's ""Revolution 9"" (whose musique concrète approach was influenced by Yoko Ono).",1,positive
15,"[SUBJECT] The Beatles [CANDIDATE] Elvis Presley [CONTEXT] The Beatles' earliest influences include Elvis Presley, Carl Perkins, Little Richard, Chuck Berry and Gene Vincent.",1,positive
16,"[SUBJECT] The Beatles [CANDIDATE] Carl Perkins [CONTEXT] The Beatles' earliest influences include Elvis Presley, Carl Perkins, Little Richard, Chuck Berry and Gene Vincent.",1,positive
17,"[SUBJECT] The Beatles [CANDIDATE] Little Richard [CONTEXT] The Beatles' earliest influences include Elvis Presley, Carl Perkins, Little Richard, Chuck Berry and Gene Vincent.",1,positive
18,"[SUBJECT] The Beatles [CANDIDATE] Chuck Berry [CONTEXT] The Beatles' earliest influences include Elvis Presley, Carl Perkins, Little Richard, Chuck Berry and Gene Vincent.",1,positive
19,"[SUBJECT] The Beatles [CANDIDATE] Gene Vincent [CONTEXT] The Beatles' earliest influences include Elvis Presley, Carl Perkins, Little Richard, Chuck Berry and Gene Vincent.",1,positive
20,"[SUBJECT] The Beatles [CANDIDATE] Buddy Holly [CONTEXT] Other early influences include Buddy Holly, Eddie Cochran, Roy Orbison, the Everly Brothers and Jerry Lee Lewis.",1,positive
21,"[SUBJECT] The Beatles [CANDIDATE] Eddie Cochran [CONTEXT] Other early influences include Buddy Holly, Eddie Cochran, Roy Orbison, the Everly Brothers and Jerry Lee Lewis.",1,positive
22,"[SUBJECT] The Beatles [CANDIDATE] Roy Orbison [CONTEXT] Other early influences include Buddy Holly, Eddie Cochran, Roy Orbison, the Everly Brothers and Jerry Lee Lewis.",1,positive
23,"[SUBJECT] The Beatles [CANDIDATE] Everly Brothers [CONTEXT] Other early influences include Buddy Holly, Eddie Cochran, Roy Orbison, the Everly Brothers and Jerry Lee Lewis.",1,positive
24,"[SUBJECT] The Beatles [CANDIDATE] Jerry Lee Lewis [CONTEXT] Other early influences include Buddy Holly, Eddie Cochran, Roy Orbison, the Everly Brothers and Jerry Lee Lewis.",1,positive
25,[SUBJECT] Brian Eno [CANDIDATE] Piet Mondrian [CONTEXT] He was also inspired by Dutch painter Piet Mondrian.,1,positive
26,"[SUBJECT] Brian Eno [CANDIDATE] John Cage [CONTEXT] Whilst inspired by the ideas of minimalist composers including John Cage, Terry Riley, Steve Reich.",1,positive
27,"[SUBJECT] Brian Eno [CANDIDATE] Terry Riley [CONTEXT] Whilst inspired by the ideas of minimalist composers including John Cage, Terry Riley, Steve Reich.",1,positive
28,"[SUBJECT] Brian Eno [CANDIDATE] Steve Reich [CONTEXT] Whilst inspired by the ideas of minimalist composers including John Cage, Terry Riley, Steve Reich.",1,positive
29,[SUBJECT] Neil Young [CANDIDATE] Bob Dylan [CONTEXT] Mitchell recalls Young as having been highly influenced by Bob Dylan at the time.,1,positive
30,[SUBJECT] Kendrick Lamar [CANDIDATE] Mos Def [CONTEXT] He also listened and took influence from Mos Def and Snoop Dogg during his childhood.,1,positive
31,[SUBJECT] Kendrick Lamar [CANDIDATE] Snoop Dogg [CONTEXT] He also listened and took influence from Mos Def and Snoop Dogg during his childhood.,1,positive
32,[SUBJECT] Kendrick Lamar [CANDIDATE] Miles Davis [CONTEXT] To Pimp a Butterfly was influenced by the works of jazz trumpeter Miles Davis and funk collective Parliament-Funkadelic.,1,positive
33,[SUBJECT] Kendrick Lamar [CANDIDATE] Parliament-Funkadelic [CONTEXT] To Pimp a Butterfly was influenced by the works of jazz trumpeter Miles Davis and funk collective Parliament-Funkadelic.,1,positive
34,[SUBJECT] Björk [CANDIDATE] Stockhausen [CONTEXT] She has cited Stockhausen as one of the people who influenced her the most.,1,positive
35,[SUBJECT] Björk [CANDIDATE] Kraftwerk [CONTEXT] She has cited Kraftwerk as one of the people who influenced her the most.,1,positive
36,[SUBJECT] Björk [CANDIDATE] Steve Reich [CONTEXT] She has cited Steve Reich as one of the people who influenced her the most.,1,positive
37,[SUBJECT] Björk [CANDIDATE] Brian Eno [CONTEXT] She has cited Brian Eno as one of the people who influenced her the most.,1,positive
38,[SUBJECT] Björk [CANDIDATE] Mark Bell [CONTEXT] She has cited Mark Bell as one of the people who influenced her the most.,1,positive
39,"[SUBJECT] The Velvet Underground [CANDIDATE] Leopold von Sacher-Masoch [CONTEXT] ""Venus in Furs"" was inspired by Leopold von Sacher-Masoch's book of the same name.",1,positive
40,"[SUBJECT] The Velvet Underground [CANDIDATE] Bo Diddley [CONTEXT] The other members were fans of doo-wop, Bo Diddley, and Booker T. & the M.G.s.",1,positive
41,[SUBJECT] The Velvet Underground [CANDIDATE] John Cage [CONTEXT] Cale brought classically-trained ideas and the influence of avant-garde composers John Cage and La Monte Young.,1,positive
42,[SUBJECT] The Velvet Underground [CANDIDATE] La Monte Young [CONTEXT] Cale brought classically-trained ideas and the influence of avant-garde composers John Cage and La Monte Young.,1,positive
43,"[SUBJECT] The Velvet Underground [CANDIDATE] Booker T. & the M.G.s [CONTEXT] The other members were fans of doo-wop, Bo Diddley, and Booker T. & the M.G.s.",1,positive
44,"[SUBJECT] Bob Dylan [CANDIDATE] Jacques Levy [CONTEXT] Many of Desire's songs featuring a travelogue-like narrative style, influenced by Dylan's collaborator, playwright Jacques Levy.",1,positive
45,[SUBJECT] Brian Eno [CANDIDATE] Piet Mondrian [CONTEXT] He was also inspired by Dutch painter Piet Mondrian.,1,positive
46,[SUBJECT] Neil Young [CANDIDATE] Bob Dylan [CONTEXT] Mitchell recalls Young as having been highly influenced by Bob Dylan at the time.,1,positive
47,[SUBJECT] Kendrick Lamar [CANDIDATE] Snoop Dogg [CONTEXT] He also listened and took influence from Mos Def and Snoop Dogg during his childhood.,1,positive
48,"[SUBJECT] The Beatles [CANDIDATE] Little Richard [CONTEXT] The Beatles' earliest influences include Elvis Presley, Carl Perkins, Little Richard, Chuck Berry and Gene Vincent.",1,positive
49,"[SUBJECT] The Velvet Underground [CANDIDATE] Booker T. & the M.G.s [CONTEXT] The other members were fans of doo-wop, Bo Diddley, and Booker T. & the M.G.s.",1,positive
50,[SUBJECT] Radiohead [CANDIDATE] Krzysztof Penderecki [CONTEXT] Jonny Greenwood cited the influence of the 20th-century classical composers Krzysztof Penderecki and Olivier Messiaen.,1,positive
51,"[SUBJECT] Sonic Youth [CANDIDATE] Velvet Underground [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
52,"[SUBJECT] Sonic Youth [CANDIDATE] Stooges [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
53,"[SUBJECT] Sonic Youth [CANDIDATE] MC5 [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
54,"[SUBJECT] Sonic Youth [CANDIDATE] Glenn Branca [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
55,"[SUBJECT] Sonic Youth [CANDIDATE] Rhys Chatham [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
56,"[SUBJECT] Sonic Youth [CANDIDATE] Ornette Coleman [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
57,"[SUBJECT] Sonic Youth [CANDIDATE] John Coltrane [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
58,"[SUBJECT] Sonic Youth [CANDIDATE] La Monte Young [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
59,"[SUBJECT] Sonic Youth [CANDIDATE] Neil Young [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
60,"[SUBJECT] Sonic Youth [CANDIDATE] Yoko Ono [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
61,"[SUBJECT] Sonic Youth [CANDIDATE] Brigitte Fontaine [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
62,"[SUBJECT] Sonic Youth [CANDIDATE] Patti Smith [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
63,"[SUBJECT] Sonic Youth [CANDIDATE] Wire [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
64,"[SUBJECT] Sonic Youth [CANDIDATE] Public Image Ltd [CONTEXT] Sonic Youth was heavily influenced by the Velvet Underground, the Stooges, MC5, Glenn Branca, Rhys Chatham, Ornette Coleman, John Coltrane, La Monte Young, Neil Young, Yoko Ono, Brigitte Fontaine, Patti Smith, Wire, and Public Image Ltd.",1,positive
65,"[SUBJECT] R.E.M. [CANDIDATE] Patti Smith [CONTEXT] The pair discovered that they shared similar tastes in music, particularly in punk rock and proto-punk artists like Patti Smith, Television, and the Velvet Underground.",1,positive
66,"[SUBJECT] R.E.M. [CANDIDATE] T. Rex [CONTEXT] Musically, Stipe stated that bands like T. Rex and Mott the Hoople ""really impacted me"".",1,positive
67,"[SUBJECT] R.E.M. [CANDIDATE] Mott the Hoople [CONTEXT] Musically, Stipe stated that bands like T. Rex and Mott the Hoople ""really impacted me"".",1,positive
68,"[SUBJECT] The Smiths [CANDIDATE] James Honeyman-Scott [CONTEXT] Marr's jangly guitar-playing was influenced by James Honeyman-Scott of the Pretenders, and Bert Jansch of Pentangle.",1,positive
69,"[SUBJECT] The Smiths [CANDIDATE] Bert Jansch [CONTEXT] Marr's jangly guitar-playing was influenced by James Honeyman-Scott of the Pretenders, and Bert Jansch of Pentangle.",1,positive
70,"[SUBJECT] The Smiths [CANDIDATE] New York Dolls [CONTEXT] Morrissey's songwriting was influenced by punk rock and post-punk bands such as New York Dolls, the Cramps, the Specials and the Cult.",1,positive
71,"[SUBJECT] The Smiths [CANDIDATE] the Cramps [CONTEXT] Morrissey's songwriting was influenced by punk rock and post-punk bands such as New York Dolls, the Cramps, the Specials and the Cult.",1,positive
72,"[SUBJECT] The Smiths [CANDIDATE] the Cult [CONTEXT] Morrissey's songwriting was influenced by punk rock and post-punk bands such as New York Dolls, the Cramps, the Specials and the Cult.",1,positive
73,"[SUBJECT] The Smiths [CANDIDATE] Dusty Springfield [CONTEXT] Morrissey's songwriting was influenced by 1960s girl groups and singers such as Dusty Springfield, Sandie Shaw, Marianne Faithfull and Timi Yuro.",1,positive
74,"[SUBJECT] The Smiths [CANDIDATE] Sandie Shaw [CONTEXT] Morrissey's songwriting was influenced by 1960s girl groups and singers such as Dusty Springfield, Sandie Shaw, Marianne Faithfull and Timi Yuro.",1,positive
75,"[SUBJECT] The Smiths [CANDIDATE] Marianne Faithfull [CONTEXT] Morrissey's songwriting was influenced by 1960s girl groups and singers such as Dusty Springfield, Sandie Shaw, Marianne Faithfull and Timi Yuro.",1,positive
76,"[SUBJECT] The Smiths [CANDIDATE] Timi Yuro [CONTEXT] Morrissey's songwriting was influenced by 1960s girl groups and singers such as Dusty Springfield, Sandie Shaw, Marianne Faithfull and Timi Yuro.",1,positive
77,"[SUBJECT] Joy Division [CANDIDATE] David Bowie [CONTEXT] Curtis was inspired by artists such as the Doors, Iggy Pop, David Bowie, Kraftwerk, the Velvet Underground and Neu!.",1,positive
78,"[SUBJECT] Joy Division [CANDIDATE] Kraftwerk [CONTEXT] Curtis was inspired by artists such as the Doors, Iggy Pop, David Bowie, Kraftwerk, the Velvet Underground and Neu!.",1,positive
79,"[SUBJECT] Joy Division [CANDIDATE] the Doors [CONTEXT] Curtis was inspired by artists such as the Doors, Iggy Pop, David Bowie, Kraftwerk, the Velvet Underground and Neu!.",1,positive
80,"[SUBJECT] Joy Division [CANDIDATE] Iggy Pop [CONTEXT] Curtis was inspired by artists such as the Doors, Iggy Pop, David Bowie, Kraftwerk, the Velvet Underground and Neu!.",1,positive
81,"[SUBJECT] Joy Division [CANDIDATE] Velvet Underground [CONTEXT] Curtis was inspired by artists such as the Doors, Iggy Pop, David Bowie, Kraftwerk, the Velvet Underground and Neu!.",1,positive
82,"[SUBJECT] Joy Division [CANDIDATE] Neu! [CONTEXT] Curtis was inspired by artists such as the Doors, Iggy Pop, David Bowie, Kraftwerk, the Velvet Underground and Neu!.",1,positive
83,[SUBJECT] Led Zeppelin [CANDIDATE] Muddy Waters [CONTEXT] The influence of American blues artists such as Muddy Waters and Skip James was particularly apparent on their first two albums.,1,positive
84,[SUBJECT] Led Zeppelin [CANDIDATE] Skip James [CONTEXT] The influence of American blues artists such as Muddy Waters and Skip James was particularly apparent on their first two albums.,1,positive
85,[SUBJECT] Led Zeppelin [CANDIDATE] Howlin' Wolf [CONTEXT] The influence of American blues artists such as Muddy Waters and Skip James was particularly apparent on their first two albums.,1,positive
86,[SUBJECT] Led Zeppelin [CANDIDATE] J. R. R. Tolkien [CONTEXT] Plant's songwriting was inspired by J. R. R. Tolkien's high fantasy novel The Lord of the Rings.,1,positive
87,"[SUBJECT] Black Sabbath [CANDIDATE] Cream [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
88,"[SUBJECT] Black Sabbath [CANDIDATE] the Beatles [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
89,"[SUBJECT] Black Sabbath [CANDIDATE] Fleetwood Mac [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
90,"[SUBJECT] Black Sabbath [CANDIDATE] Jimi Hendrix [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
91,"[SUBJECT] Black Sabbath [CANDIDATE] John Mayall & the Bluesbreakers [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
92,"[SUBJECT] Black Sabbath [CANDIDATE] Blue Cheer [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
93,"[SUBJECT] Black Sabbath [CANDIDATE] Golden Earring [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
94,"[SUBJECT] Black Sabbath [CANDIDATE] Led Zeppelin [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
95,"[SUBJECT] Black Sabbath [CANDIDATE] Jethro Tull [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
96,"[SUBJECT] Black Sabbath [CANDIDATE] Iron Butterfly [CONTEXT] Early on, Black Sabbath were influenced by Cream, the Beatles, Fleetwood Mac, Jimi Hendrix, John Mayall & the Bluesbreakers, Blue Cheer, Golden Earring, Led Zeppelin, Jethro Tull, and Iron Butterfly.",1,positive
97,"[SUBJECT] Black Sabbath [CANDIDATE] Django Reinhardt [CONTEXT] Inspired by Django Reinhardt, Iommi created two thimbles to cap off his missing fingertips.",1,positive
98,"[SUBJECT] Black Sabbath [CANDIDATE] Dennis Wheatley [CONTEXT] The lyrics for ""Black Sabbath"" were inspired by the work of horror writer Dennis Wheatley.",1,positive
99,"[SUBJECT] Tyler, the Creator [CANDIDATE] Eminem [CONTEXT] The horrorcore-based aesthetics and transgressive lyrical content of his debut and second albums Bastard and Goblin were influenced by Eminem.",1,positive
100,"[SUBJECT] Billie Eilish [CANDIDATE] Adele [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
101,"[SUBJECT] Billie Eilish [CANDIDATE] Earl Sweatshirt [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
102,"[SUBJECT] Billie Eilish [CANDIDATE] James Blake [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
103,"[SUBJECT] Billie Eilish [CANDIDATE] Amy Winehouse [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
104,"[SUBJECT] Billie Eilish [CANDIDATE] Lorde [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
105,"[SUBJECT] Billie Eilish [CANDIDATE] Marina [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
106,"[SUBJECT] Billie Eilish [CANDIDATE] Britney Spears [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
107,"[SUBJECT] Billie Eilish [CANDIDATE] Taylor Swift [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
108,"[SUBJECT] Billie Eilish [CANDIDATE] Nicki Minaj [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
109,"[SUBJECT] Billie Eilish [CANDIDATE] XXXTentacion [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
110,"[SUBJECT] Billie Eilish [CANDIDATE] Twenty One Pilots [CONTEXT] Other influences include Adele, Earl Sweatshirt, James Blake, Amy Winehouse, the Spice Girls, Lorde, Marina, Britney Spears, Taylor Swift, Nicki Minaj, XXXTentacion, and Twenty One Pilots.",1,positive
111,"[SUBJECT] Lana Del Rey [CANDIDATE] Andrew Lloyd Webber [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
112,"[SUBJECT] Lana Del Rey [CANDIDATE] Frank Sinatra [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
113,"[SUBJECT] Lana Del Rey [CANDIDATE] Nina Simone [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
114,"[SUBJECT] Lana Del Rey [CANDIDATE] Billie Holiday [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
115,"[SUBJECT] Lana Del Rey [CANDIDATE] Bobby Vinton [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
116,"[SUBJECT] Lana Del Rey [CANDIDATE] The Crystals [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
117,"[SUBJECT] Lana Del Rey [CANDIDATE] Brian Wilson [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
118,"[SUBJECT] Lana Del Rey [CANDIDATE] Nancy Sinatra [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
119,"[SUBJECT] Lana Del Rey [CANDIDATE] Miles Davis [CONTEXT] Del Rey cites a wide array of musical artists as influences, including Andrew Lloyd Webber, Frank Sinatra, Nina Simone, Billie Holiday, Bobby Vinton, The Crystals, Brian Wilson, Nancy Sinatra, and Miles Davis.",1,positive
120,"[SUBJECT] Lana Del Rey [CANDIDATE] Walt Whitman [CONTEXT] Inspired by poetry, Del Rey cites Walt Whitman and Allen Ginsberg as instrumental to her songwriting.",1,positive
121,"[SUBJECT] Lana Del Rey [CANDIDATE] Allen Ginsberg [CONTEXT] Inspired by poetry, Del Rey cites Walt Whitman and Allen Ginsberg as instrumental to her songwriting.",1,positive
122,[SUBJECT] The Weeknd [CANDIDATE] Aster Aweke [CONTEXT] His high-flying vocal style was influenced by Ethiopian singers such as Aster Aweke.,1,positive
123,[SUBJECT] The Weeknd [CANDIDATE] Deftones [CONTEXT] Tesfaye has named Deftones as one of his influences.,1,positive
124,[SUBJECT] The Weeknd [CANDIDATE] Jean-Michel Basquiat [CONTEXT] Tesfaye's hairstyle has been claimed to be partly inspired by artist Jean-Michel Basquiat.,1,positive
125,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Bright Eyes [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
126,"[SUBJECT] Phoebe Bridgers [CANDIDATE] the Replacements [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
127,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Blake Mills [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
128,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Tom Waits [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
129,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Avril Lavigne [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
130,"[SUBJECT] Phoebe Bridgers [CANDIDATE] the Beatles [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
131,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Jackson Browne [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
132,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Taylor Swift [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
133,"[SUBJECT] Phoebe Bridgers [CANDIDATE] Nine Inch Nails [CONTEXT] Other musical influences include Bright Eyes, the Replacements, Blake Mills, Tom Waits, Avril Lavigne, the Beatles, Jackson Browne, Taylor Swift and Nine Inch Nails.",1,positive
134,[SUBJECT] Grimes [CANDIDATE] Hildegard of Bingen [CONTEXT] The theories of her album Halfaxa were inspired by Hildegard of Bingen.,1,positive
135,[SUBJECT] Grimes [CANDIDATE] David Bowie [CONTEXT] Grimes described a song as inspired by David Bowie.,1,positive
136,[SUBJECT] Grimes [CANDIDATE] Queen [CONTEXT] Grimes described a song as inspired by David Bowie and Queen.,1,positive
137,[SUBJECT] Grimes [CANDIDATE] Billy Joel [CONTEXT] Art Angels was influenced by Billy Joel.,1,positive
138,[SUBJECT] Grimes [CANDIDATE] Bruce Springsteen [CONTEXT] Art Angels was influenced by Bruce Springsteen.,1,positive
139,"[SUBJECT] Grimes [CANDIDATE] Jedi Mind Tricks [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
140,"[SUBJECT] Grimes [CANDIDATE] Kenji Kawai [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
141,"[SUBJECT] Grimes [CANDIDATE] Yoko Kanno [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
142,"[SUBJECT] Grimes [CANDIDATE] Alicia Keys [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
143,"[SUBJECT] Grimes [CANDIDATE] Christina Aguilera [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
144,"[SUBJECT] Grimes [CANDIDATE] Panda Bear [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
145,"[SUBJECT] Grimes [CANDIDATE] Bikini Kill [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
146,"[SUBJECT] Grimes [CANDIDATE] Kate Bush [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
147,"[SUBJECT] Grimes [CANDIDATE] Al Green [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
148,"[SUBJECT] Grimes [CANDIDATE] Salem [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
149,"[SUBJECT] Grimes [CANDIDATE] Trent Reznor [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
150,"[SUBJECT] Grimes [CANDIDATE] Tool [CONTEXT] Some of her other influences include Jedi Mind Tricks, Kenji Kawai, Yoko Kanno, Alicia Keys, Christina Aguilera, Panda Bear, Bikini Kill, Kate Bush, Al Green, Salem, Trent Reznor, Tool.",1,positive
151,"[SUBJECT] Childish Gambino [CANDIDATE] Ghostface Killah [CONTEXT] Glover stated ""I'm influenced by LCD Soundsystem as much as Ghostface Killah.""",1,positive
152,"[SUBJECT] Childish Gambino [CANDIDATE] LCD Soundsystem [CONTEXT] Glover stated ""I'm influenced by LCD Soundsystem as much as Ghostface Killah.""",1,positive
153,"[SUBJECT] Travis Scott [CANDIDATE] Bon Iver [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
154,"[SUBJECT] Travis Scott [CANDIDATE] Kid Cudi [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
155,"[SUBJECT] Travis Scott [CANDIDATE] M.I.A. [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
156,"[SUBJECT] Travis Scott [CANDIDATE] Kanye West [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
157,"[SUBJECT] Travis Scott [CANDIDATE] Toro y Moi [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
158,"[SUBJECT] Travis Scott [CANDIDATE] Tame Impala [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
159,"[SUBJECT] Travis Scott [CANDIDATE] T.I. [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
160,"[SUBJECT] Travis Scott [CANDIDATE] Thom Yorke [CONTEXT] He is also influenced by Bon Iver, Kid Cudi, M.I.A., Kanye West, Toro y Moi, Tame Impala, T.I., and Thom Yorke.",1,positive
161,[SUBJECT] Travis Scott [CANDIDATE] Mike Dean [CONTEXT] Scott's production style is predominantly influenced by producers Mike Dean and Alex Tumay.,1,positive
162,[SUBJECT] Travis Scott [CANDIDATE] Alex Tumay [CONTEXT] Scott's production style is predominantly influenced by producers Mike Dean and Alex Tumay.,1,positive
163,"[SUBJECT] Playboi Carti [CANDIDATE] Lil Wayne [CONTEXT] Almost all of Carter's raps are freestyled, which was directly inspired by Lil Wayne.",1,positive
164,"[SUBJECT] Playboi Carti [CANDIDATE] Wiz Khalifa [CONTEXT] He recorded songs influenced by Wiz Khalifa, Currensy, and Odd Future.",1,positive
165,"[SUBJECT] Playboi Carti [CANDIDATE] Currensy [CONTEXT] He recorded songs influenced by Wiz Khalifa, Currensy, and Odd Future.",1,positive
166,"[SUBJECT] Playboi Carti [CANDIDATE] Odd Future [CONTEXT] He recorded songs influenced by Wiz Khalifa, Currensy, and Odd Future.",1,positive
167,"[SUBJECT] Billie Eilish [CANDIDATE] Beatles [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
168,"[SUBJECT] Billie Eilish [CANDIDATE] Justin Bieber [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
169,"[SUBJECT] Billie Eilish [CANDIDATE] Green Day [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
170,"[SUBJECT] Billie Eilish [CANDIDATE] the 1975 [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
171,"[SUBJECT] Billie Eilish [CANDIDATE] Arctic Monkeys [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
172,"[SUBJECT] Billie Eilish [CANDIDATE] Nine Inch Nails [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
173,"[SUBJECT] Billie Eilish [CANDIDATE] Linkin Park [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
174,"[SUBJECT] Billie Eilish [CANDIDATE] Lana Del Rey [CONTEXT] Eilish grew up listening to the Beatles, Justin Bieber, Green Day, the 1975, Arctic Monkeys, Nine Inch Nails, Linkin Park and Lana Del Rey.",1,positive
175,"[SUBJECT] John Coltrane [CANDIDATE] Lester Young [CONTEXT] While in high school, Coltrane played clarinet and alto horn in a community band before switching to the saxophone, after being influenced by the likes of Lester Young and Johnny Hodges.",1,positive
176,"[SUBJECT] John Coltrane [CANDIDATE] Johnny Hodges [CONTEXT] While in high school, Coltrane played clarinet and alto horn in a community band before switching to the saxophone, after being influenced by the likes of Lester Young and Johnny Hodges.",1,positive
177,[SUBJECT] Herbie Hancock [CANDIDATE] The Hi-Lo's [CONTEXT] Hancock was also influenced by records of the vocal group the Hi-Lo's.,1,positive
178,"[SUBJECT] Herbie Hancock [CANDIDATE] Bill Evans [CONTEXT] Clare Fischer was a major influence on my harmonic concept... he and Bill Evans, and Ravel and Gil Evans, finally.",1,positive
179,"[SUBJECT] Herbie Hancock [CANDIDATE] Ravel [CONTEXT] Clare Fischer was a major influence on my harmonic concept... he and Bill Evans, and Ravel and Gil Evans, finally.",1,positive
180,"[SUBJECT] Herbie Hancock [CANDIDATE] Gil Evans [CONTEXT] Clare Fischer was a major influence on my harmonic concept... he and Bill Evans, and Ravel and Gil Evans, finally.",1,positive
181,"[SUBJECT] Aphex Twin [CANDIDATE] Luke Vibert [CONTEXT] When James began programming faster, jungle-inspired breakbeats in the mid-1990s, he named friends and fellow musicians Luke Vibert and Tom Jenkinson as influences.",1,positive
182,"[SUBJECT] Aphex Twin [CANDIDATE] Tom Jenkinson [CONTEXT] When James began programming faster, jungle-inspired breakbeats in the mid-1990s, he named friends and fellow musicians Luke Vibert and Tom Jenkinson as influences.",1,positive
183,"[SUBJECT] Kraftwerk [CANDIDATE] James Brown [CONTEXT] Kraftwerk have been recognised as pioneers of electronic music. The group was also inspired by the funk music of James Brown and, later, punk rock.",1,positive
184,"[SUBJECT] Kraftwerk [CANDIDATE] Karlheinz Stockhausen [CONTEXT] In its early incarnation, the band pursued an avant-garde, experimental rock style inspired by the compositions of Karlheinz Stockhausen.",1,positive
185,"[SUBJECT] Kraftwerk [CANDIDATE] Bauhaus [CONTEXT] They were influenced by the modernist Bauhaus aesthetic, seeing art as inseparable from everyday function.",1,positive
186,"[SUBJECT] Daft Punk [CANDIDATE] Andy Warhol [CONTEXT] In 2009, Bangalter named Andy Warhol as one of Daft Punk's early influences.",1,positive
187,"[SUBJECT] Boards of Canada [CANDIDATE] Meat Beat Manifesto [CONTEXT] They have also named Meat Beat Manifesto as a chief influence, citing their synth sounds.",1,positive
188,"[SUBJECT] Lorde [CANDIDATE] Sam Cooke [CONTEXT] Lorde grew up listening to American jazz and soul musicians Billie Holiday, Sam Cooke, Etta James, and Otis Redding.",1,positive
189,"[SUBJECT] Lorde [CANDIDATE] Etta James [CONTEXT] Lorde grew up listening to American jazz and soul musicians Billie Holiday, Sam Cooke, Etta James, and Otis Redding.",1,positive
190,"[SUBJECT] Lorde [CANDIDATE] Otis Redding [CONTEXT] Lorde grew up listening to American jazz and soul musicians Billie Holiday, Sam Cooke, Etta James, and Otis Redding.",1,positive
191,"[SUBJECT] Charli XCX [CANDIDATE] Britney Spears [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
192,"[SUBJECT] Charli XCX [CANDIDATE] Shampoo [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
193,"[SUBJECT] Charli XCX [CANDIDATE] No Doubt [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
194,"[SUBJECT] Charli XCX [CANDIDATE] t.A.T.u. [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
195,"[SUBJECT] Charli XCX [CANDIDATE] the Donnas [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
196,"[SUBJECT] Charli XCX [CANDIDATE] Bikini Kill [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
197,"[SUBJECT] Charli XCX [CANDIDATE] Martika [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
198,"[SUBJECT] Charli XCX [CANDIDATE] Björk [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
199,"[SUBJECT] Charli XCX [CANDIDATE] Donna Summer [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
200,"[SUBJECT] Charli XCX [CANDIDATE] Bread [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
201,"[SUBJECT] Charli XCX [CANDIDATE] Uffie [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
202,"[SUBJECT] Charli XCX [CANDIDATE] Lil Wayne [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
203,"[SUBJECT] Charli XCX [CANDIDATE] Lily Allen [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
204,"[SUBJECT] Charli XCX [CANDIDATE] Kate Bush [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
205,"[SUBJECT] Charli XCX [CANDIDATE] Justice [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
206,"[SUBJECT] Charli XCX [CANDIDATE] Crystal Castles [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
207,"[SUBJECT] Charli XCX [CANDIDATE] Calvin Harris [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
208,"[SUBJECT] Charli XCX [CANDIDATE] Daft Punk [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
209,"[SUBJECT] Charli XCX [CANDIDATE] Sebastian [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
210,"[SUBJECT] Charli XCX [CANDIDATE] Honey Dijon [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
211,"[SUBJECT] Charli XCX [CANDIDATE] Robyn [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
212,"[SUBJECT] Charli XCX [CANDIDATE] Autechre [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
213,"[SUBJECT] Charli XCX [CANDIDATE] Aphex Twin [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
214,"[SUBJECT] Charli XCX [CANDIDATE] Quentin Tarantino [CONTEXT] Charli XCX's influences include Britney Spears, Shampoo, No Doubt, t.A.T.u., the Donnas, Bikini Kill, Martika, Björk, Siouxsie and the Banshees, the Feminine Complex, Donna Summer, Bread, All Saints, Uffie, Brooke Candy, Lil Wayne, Lily Allen, Kate Bush, Twin Peaks, Paris Hilton, Justice, Crystal Castles, Calvin Harris, Daft Punk, Sebastian, Honey Dijon, Robyn, Arca, M.I.A., Autechre, Aphex Twin, and Quentin Tarantino.",1,positive
215,"[SUBJECT] SZA [CANDIDATE] RZA [CONTEXT] She took cues from the Supreme Alphabet, taking influence from rappers RZA and GZA of Wu-Tang Clan.",1,positive
216,"[SUBJECT] SZA [CANDIDATE] GZA [CONTEXT] She took cues from the Supreme Alphabet, taking influence from rappers RZA and GZA of Wu-Tang Clan.",1,positive
217,"[SUBJECT] Slowdive [CANDIDATE] Pink Floyd [CONTEXT] Music journalist Simon Reynolds wrote that ""Halstead was more influenced by Pink Floyd than by the Sex Pistols.""",1,positive
218,"[SUBJECT] The Roots [CANDIDATE] RZA [CONTEXT] The band's sound would take a darker turn during this period, heavily influenced by the Wu-Tang Clan and the RZA's grimy and haunting production style, replete with samples from old jazz and classical music.",1,positive
219,"[SUBJECT] The Roots [CANDIDATE] Wu-Tang Clan [CONTEXT] The band's sound would take a darker turn during this period, heavily influenced by the Wu-Tang Clan and the RZA's grimy and haunting production style, replete with samples from old jazz and classical music.",1,positive
